version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true
    networks:
      - custom_network


networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.42.12.0/28
          gateway: 172.42.12.1